server:
  port: 8081

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:mydb
    username: root
    password: root
    driver-class-name: org.h2.Driver
logging:
  level:
    root: DEBUG

